name: publish package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          sed -i 's/"name": "project-manager"/"name": "pm-gui"/' package.json
          sed -i '/"dependencies": {/,/}/{//!d}' package.json
          sed -i '/"devDependencies": {/,/}/{//!d}' package.json
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
